name: "Pull Request Tests"

on:
  pull_request:
    # Run this workflow on pull requests for all branches.
    branches: ["*"]

jobs:
  test:
    name: Run Python Tests on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest

      - name: Run tests using Makefile target
        run: python -m pytest