name: Publish Python Package to PyPI

on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Commitizen
      run: |
        pip install commitizen

    - name: Generate Version Tag with Commitizen
      id: tag
      run: |
        git fetch --tags
        cz bump --yes --dry-run
#         NEW_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
#         echo "New tag: $NEW_TAG"
#         echo "::set-output name=new_tag::$NEW_TAG"

#    - name: Publish to PyPI
#      if: steps.tag.outputs.new_tag != ''
#      run: |
#        python -m pip install --upgrade pip
#        pip install twine
#        python setup.py sdist bdist_wheel
#        twine upload dist/*